/**
 * sync-stats.mjs — Generate personas/*.md from .template.md + remote stats.json
 *
 * Reads stats.json from flowmcp-schemas-public (raw GitHub or local override),
 * substitutes {{stats.<key>}} placeholders (including derived locale formats
 * count_tools_de / count_tools_en) in template files, and writes target
 * personas/*.md files with a generator-marker header.
 *
 * Source-of-Truth: flowmcp-schemas-public/stats.json
 * Targets:
 *   - personas/vision.md       (from personas/vision.md.template)
 *   - personas/vision-snippets.md
 *   - personas/tone-guide.md
 *
 * Usage: npm run sync-stats
 *   Override stats source: STATS_URL=file://./local.json npm run sync-stats
 *
 * Memo 060 Phase 8 / PRD-025 Task D.
 */

import { readFile, writeFile, access } from 'node:fs/promises'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'


const __filename = fileURLToPath( import.meta.url )
const __dirname = dirname( __filename )
const REPO_ROOT = resolve( __dirname, '..' )
const PERSONAS_DIR = join( REPO_ROOT, 'personas' )

const DEFAULT_STATS_URL = 'https://raw.githubusercontent.com/FlowMCP/flowmcp-schemas-public/main/stats.json'

const PLACEHOLDER_REGEX = /\{\{stats\.([a-zA-Z0-9_]+)\}\}/g

const TARGETS = [
    { template: 'vision.md.template', output: 'vision.md' },
    { template: 'vision-snippets.md.template', output: 'vision-snippets.md' },
    { template: 'tone-guide.md.template', output: 'tone-guide.md' }
]


const fileExists = async ( { path } ) => {
    try {
        await access( path )
        return true
    } catch( _ ) {
        return false
    }
}


const sanitizeSource = ( { url } ) => {
    if( !url.startsWith( 'file://' ) ) { return url }
    return 'file://(local stats.json)'
}


const loadStats = async () => {
    const url = process.env.STATS_URL || DEFAULT_STATS_URL
    if( url.startsWith( 'file://' ) ) {
        const localPath = url.replace( 'file://', '' )
        const raw = await readFile( localPath, 'utf-8' )
        const stats = JSON.parse( raw )
        return { stats, source: sanitizeSource( { url } ) }
    }
    const response = await fetch( url )
    if( !response.ok ) {
        throw new Error( `HTTP ${ response.status } ${ response.statusText } for ${ url }` )
    }
    const stats = await response.json()
    return { stats, source: url }
}


const deriveLocaleVariants = ( { stats } ) => {
    const enriched = { ...stats }
    if( typeof stats.count_tools === 'number' ) {
        enriched.count_tools_de = stats.count_tools.toLocaleString( 'de-DE' )
        enriched.count_tools_en = stats.count_tools.toLocaleString( 'en-US' )
    }
    if( typeof stats.count_schemas === 'number' ) {
        enriched.count_schemas_de = stats.count_schemas.toLocaleString( 'de-DE' )
        enriched.count_schemas_en = stats.count_schemas.toLocaleString( 'en-US' )
    }
    return { enriched }
}


const renderTemplate = ( { content, stats } ) => {
    const unresolved = []
    const rendered = content.replace( PLACEHOLDER_REGEX, ( match, key ) => {
        if( !Object.prototype.hasOwnProperty.call( stats, key ) ) {
            unresolved.push( key )
            return match
        }
        const value = stats[ key ]
        if( value === null || value === undefined ) {
            unresolved.push( key )
            return match
        }
        return String( value )
    } )
    return { rendered, unresolved }
}


const buildHeader = ( { source, schemaVersion, buildHash, timestamp } ) => {
    const lines = [
        `<!-- generated by scripts/sync-stats.mjs at ${ new Date().toISOString() } -->`,
        `<!-- source: ${ source } | schema_version=${ schemaVersion } build_hash=${ buildHash } stats_timestamp=${ timestamp } -->`,
        ''
    ]
    return lines.join( '\n' )
}


const processTarget = async ( { templateName, outputName, stats, source } ) => {
    const templatePath = join( PERSONAS_DIR, templateName )
    const outputPath = join( PERSONAS_DIR, outputName )
    const exists = await fileExists( { path: templatePath } )
    if( !exists ) {
        console.warn( `[sync-stats] template missing: ${ templatePath } — skip` )
        return { skipped: true }
    }
    const template = await readFile( templatePath, 'utf-8' )
    const { rendered, unresolved } = renderTemplate( { content: template, stats } )
    if( unresolved.length > 0 ) {
        throw new Error( `[sync-stats] ${ templatePath }: unresolved placeholders -> ${ unresolved.join( ', ' ) }` )
    }
    const header = buildHeader( {
        source,
        schemaVersion: stats.schema_version,
        buildHash: stats.build_hash,
        timestamp: stats.timestamp
    } )
    const final = header + rendered
    await writeFile( outputPath, final, 'utf-8' )
    console.log( `[sync-stats] ${ templatePath } -> ${ outputPath }` )
    return { skipped: false }
}


const main = async () => {
    const { stats, source } = await loadStats()
    const { enriched } = deriveLocaleVariants( { stats } )

    console.log( `[sync-stats] source: ${ source }` )
    console.log( `[sync-stats] stats: schemas=${ enriched.count_schemas } tools=${ enriched.count_tools } (de=${ enriched.count_tools_de }, en=${ enriched.count_tools_en }) datasources=${ enriched.count_unique_datasources }` )

    await Promise.all( TARGETS.map( ( { template, output } ) => {
        return processTarget( {
            templateName: template,
            outputName: output,
            stats: enriched,
            source
        } )
    } ) )

    console.log( `[sync-stats] processed ${ TARGETS.length } targets` )
}


const isCli = import.meta.url === pathToFileURL( process.argv[ 1 ] ).href
if( isCli ) {
    main()
        .catch( ( err ) => {
            console.error( `[sync-stats] ERROR: ${ err.message }` )
            process.exit( 1 )
        } )
}
